package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import java.net.URLEncoder

object AlertManager {

    /**
     * Sends an SMS alert to the student's guardian about their absence.
     */
    fun sendAbsenceSms(
        context: Context,
        guardianPhone: String?,
        studentName: String,
        rollNumber: String,
        subjectName: String,
        date: String
    ) {
        val message = "Dear Guardian, your ward $studentName (Roll: $rollNumber) was marked ABSENT today ($date) in the subject '$subjectName'. Please contact the department if this was unexpected. - Teacher Student Manager"

        try {
            val smsUri = if (!guardianPhone.isNullOrBlank()) {
                Uri.parse("smsto:${guardianPhone.trim()}")
            } else {
                Uri.parse("smsto:")
            }
            val intent = Intent(Intent.ACTION_SENDTO, smsUri).apply {
                putExtra("sms_body", message)
            }
            context.startActivity(intent)
        } catch (e: Exception) {
            Toast.makeText(context, "Could not open SMS app: ${e.localizedMessage}", Toast.LENGTH_SHORT).show()
        }
    }

    /**
     * Sends a WhatsApp notification to the guardian.
     */
    fun sendAbsenceWhatsApp(
        context: Context,
        guardianPhone: String?,
        studentName: String,
        rollNumber: String,
        subjectName: String,
        date: String
    ) {
        val message = "Dear Guardian, your ward $studentName (Roll: $rollNumber) was marked ABSENT today ($date) in the subject '$subjectName'. Please contact the institution for further inquiries. - Teacher Student Manager"

        try {
            val cleanPhone = guardianPhone?.replace(Regex("[^0-9+]"), "") ?: ""
            val url = if (cleanPhone.isNotBlank()) {
                "https://api.whatsapp.com/send?phone=$cleanPhone&text=${URLEncoder.encode(message, "UTF-8")}"
            } else {
                "https://api.whatsapp.com/send?text=${URLEncoder.encode(message, "UTF-8")}"
            }
            val intent = Intent(Intent.ACTION_VIEW, Uri.parse(url))
            context.startActivity(intent)
        } catch (e: Exception) {
            // Fallback to generic share
            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_TEXT, message)
            }
            context.startActivity(Intent.createChooser(shareIntent, "Share Absence Alert"))
        }
    }

    /**
     * Shares a comprehensive attendance and marks report for an individual student directly with parents.
     */
    fun shareStudentReportWithParent(
        context: Context,
        studentName: String,
        rollNumber: String,
        department: String,
        semester: String,
        subject: String,
        totalClasses: Int,
        present: Int,
        absent: Int,
        percentage: Double,
        ctAvg: Double?,
        midTerm: Double?
    ) {
        val pctStr = String.format(java.util.Locale.US, "%.1f%%", percentage)
        val ctStr = ctAvg?.let { String.format(java.util.Locale.US, "%.1f", it) } ?: "Not graded"
        val midStr = midTerm?.let { String.format(java.util.Locale.US, "%.1f", it) } ?: "Not graded"

        val reportText = """
            ACADEMIC PROGRESS REPORT
            Student: $studentName
            Roll No: $rollNumber
            Dept: $department | Semester: $semester
            Subject: $subject
            
            --- ATTENDANCE SUMMARY ---
            Classes Held: $totalClasses
            Attended: $present
            Absent: $absent
            Attendance Rate: $pctStr
            
            --- MARKS EVALUATION ---
            Class Test Avg: $ctStr
            Mid-Term Exam: $midStr
            
            Generated by Teacher Student Manager
            Developed by Khaled Hasan Shihab
        """.trimIndent()

        val shareIntent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, "Student Progress Report - $studentName ($rollNumber)")
            putExtra(Intent.EXTRA_TEXT, reportText)
        }
        context.startActivity(Intent.createChooser(shareIntent, "Send Report to Parent"))
    }
}
